import { ThemeProvider } from '@mui/material/styles';
import Head from 'next/head';
import { theme } from '@/theme';
import { CacheProvider, EmotionCache } from '@emotion/react';
import createCache from '@emotion/cache';
import { AppPropsWithLayout } from 'next/app';
import { PageProps } from 'next';

type MyAppProps = Omit<AppPropsWithLayout<PageProps>, 'pageProps'> & {
  emotionCache?: EmotionCache;
  pageProps: PageProps;
};

export default function App({
  Component,
  pageProps,
  emotionCache = createCache({ key: 'css' }),
}: MyAppProps) {
  const getLayout = Component.getLayout ?? ((page) => page);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CacheProvider value={emotionCache}>
        <ThemeProvider theme={theme}>
          {getLayout(<Component {...pageProps} />)}
        </ThemeProvider>
      </CacheProvider>
    </>
  );
}
