import { ThemeProvider } from '@mui/material/styles';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { theme } from '@/theme';
import { CacheProvider, EmotionCache } from '@emotion/react';
import createCache from '@emotion/cache';
import { PageProps } from 'next';
import ModalProvider from '@/providers/ModalProvider';

type MyAppProps = Omit<AppProps<PageProps>, 'pageProps'> & {
  emotionCache?: EmotionCache;
  pageProps: PageProps;
};

export default function App({
  Component,
  pageProps,
  emotionCache = createCache({ key: 'css' }),
}: MyAppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CacheProvider value={emotionCache}>
        <ThemeProvider theme={theme}>
          <ModalProvider withModal={pageProps.withModal}>
            <Component {...pageProps} />
          </ModalProvider>
        </ThemeProvider>
      </CacheProvider>
    </>
  );
}
