import Head from 'next/head';
import { Button } from '@mui/material';
import { useState } from 'react';
import Modal from '@/components/Modal';

export default function Home() {
  const [open, setOpen] = useState<boolean>(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>モーダル+url+レスポンシブサンプル</h1>
        <Button onClick={handleOpen}>モーダルを開く</Button>
        <Modal open={open} handleClose={handleClose}>
          <h3>モーダルサンプル</h3>
          これがサンプルです
        </Modal>
      </main>
    </>
  );
}
